### PR TITLE
Feat: add stopped time in manage timers

### PR DESCRIPTION
**Pull request by benqqqq**
Hi @ThatNerdSquared ,

I have added a stopped time at the end of the line in the "manage timers" command, 
which makes it easier for users to know when the timers have stopped.

Additionally, I created a new file called "timeCalculationUtils" and added the function "getTimeAfterSeconds" to it.
Because I am unsure whether adding this function to the following two files is a good idea or not:

timerUtils: This file appears to be related to timers.
formatTimeUtils: This file appears to be related to time formatting.

image

### CODE REVIEW

**Comment by ThatNerdSquared** [comment]
Hi @benqqqq, thank you so much for the contribution!

Would it be possible for you to make the following changes?
- Instead of using parens `()` around the end date, could you use "Ends at `datetime`"?
- When the timer finishes, could you show a `Finished!` tag in the same style as the "Manage Stopwatches" command?
Screenshot 2023-05-06 at 00 45 44

Let me know if you have other thoughts - once again, thanks for the PR \:)

**Comment by benqqqq** [comment]
Sure!

Does it look like this?

https://user-images.githubusercontent.com/11547758/236732761-3abf06f8-a89f-4bc8-8e1a-644d74182b7f.mov

**Review by ThatNerdSquared — COMMENTED** [review]
Hey @benqqqq, looks pretty good!

I've noticed that the end datetime:
Screenshot 2023-05-11 at 00 15 37
ticks upward when the timer completes. For example, if the timer ends at `14:20:21`, the next second, `14:20:22` will be shown, and so on.

Is this intentional? In my mind, I feel like it makes more sense for the datetime to remain static, and for the text to change to `Ended at` when the timer finishes.

Other than that, looks good \:)

**Comment by benqqqq** [comment]
Hi @ThatNerdSquared ,

To fix this bug, I changed the implementation by moving the calculation logic to timerUtils.ts and adding a timerEnds attribute to types.ts. I believe this aligns better with the original coding style. Thank you!

https://github.com/ThatNerdSquared/timers-for-raycast/assets/11547758/0444ea6f-e8e7-404e-b022-412615b5c737

**Review by ThatNerdSquared — APPROVED** [review]
Great job @benqqqq! Thanks for the contribution - looks good on both the user side and on the code side.

There'll be a short delay before this gets into the Raycast store, as I'll be PRing this change along with some small fixes/features I've been working on and it'll all need to go through review. That being said, it should be out within the next week or two 👍 

Thanks again for your PR!

**Comment by benqqqq** [comment]
Thank you for reviewing! I'm glad to be a part of it. 😄

**Pull request merged**
