### PR TITLE
fix: timer still ringing when stop

### PR DESCRIPTION
**Pull request by atuooo**
Fixed an issue where the ring continued to play even after the timer was stopped due to incorrect dismiss file path.

### CODE REVIEW

**Comment by atuooo** [comment]
https://github.com/ThatNerdSquared/timers-for-raycast/issues/9

**Comment by ThatNerdSquared** [comment]
@atuooo thank you *so much*, I cannot believe I did not catch that.

**Comment by ThatNerdSquared** [comment]
What's your Raycast dev account username, @atuooo? I'd like to add you under the contributors field in the package.json.

**Comment by atuooo** [comment]
> What's your Raycast dev account username, @atuooo? I'd like to add you under the contributors field in the package.json.

Yes. Thanks.

**Pull request merged**
