### PR TITLE
Improve stopwatch

### PR DESCRIPTION
**Pull request by ruzarh**
## Preference

image

---

## Menu bar named stopwatches

image

---

## Create custom Stopwatch form 

image

---

## Cache

image

### CODE REVIEW

**Comment by ThatNerdSquared** [comment]
Hey, thanks for the contribution! I'm currently busy so I won't be reviewing it until after Apr. 22nd - thanks for your patience.

In the meantime, would you mind explaining the rationale for some of these changes?
- Why the preset stopwatches? This exists for timers, but I never ended up implementing this for stopwatches since you can just pause and reset them.
- I'm not particularly fond of using the Raycast cache here, is there a reason why you made the switch? I wanted to keep the storage for stopwatches consistent with the timers. Also, I find it's easier to debug with the JSON file as you can easily open it, send it, etc.

Thanks! Feel free to mark the PR as ready to review when you're finished, I'll get to it sometime after the 22nd.

**Comment by ruzarh** [comment]
Storage is the same in json format, only disk handling is reduced. Also there will be no concurrent (parallel) of requests, now it is unlikely but not excluded. To fix parallel requests, you need to use semaphore. 

```[{"name":"Daily","swID":"996a4627-d84e-4f67-8bb1-62726dd74dd7","timeStarted":"2024-04-13T19:12:55.399Z","timeElapsed":-99,"lastPaused":"----","pauseElapsed":0}]```


Why the preset stopwatches? 
I track work time by task. I need about 10 timers per day for different tasks I do during the day. Some I pause, others I start, and I get confused among `Untitled` stopwatches. 

In my current situation, I can't use it comfortably. I have to rename every timer. I made a fork for myself, and I'm using it locally for now. I don't want to make a separate cut fork, maybe someone else will need it too.

**Comment by ruzarh** [comment]
I found a problem. After 6 hour a work my stopwatches was lost.  I’ve started an investigation this problem.

**Comment by ThatNerdSquared** [comment]
I suspect the use of the `Cache` API has something to do with this - maybe using the [`Storage`](https://developers.raycast.com/api-reference/storage) API would solve it?

However, that results in the stopwatches being stored in Raycast's encrypted DB, which makes it hard to just look at the data for debugging purposes. I'm not sure I would like to move the stopwatches to the Raycast Storage API.

The rest of your stopwatch preset ideas seem great, though - did you want to separate those into another PR and get that through? I have some changes I would make to integrate the presets better with the "Manage Stopwatches" command, though - so I can also just implement it myself and add you to the contributors list, if you'd like.

**Pull request closed without merging**
